version: "3.7"
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    env_file:
      - ./api/.env
    ports:
      - '5432:5432'
    volumes:
      - "db:/var/lib/postgresql/data"
    

  nndak-api:
    build: ./api
    restart: always
    depends_on:
      - postgres
    ports:
      - '8081:8080'
      - '5555:5555'
    env_file:
      - ./api/.env
    links:
      - postgres

  # nndak-ui:
  #   build: ./ui
  #   restart:  always
  #   depends_on:
  #     - nndak-api
  #   ports:
  #     - '8082:80'
  #   links:
  #     - nndak-api
  
volumes:
  db: