version: '3.7'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    env_file:
      - ./api/.env
    ports:
      - '5432:5432'
    volumes:
      - 'db:/var/lib/postgresql/data'

  nndak-api:
    build: ./api
    container_name: nndak_api
    restart: always
    depends_on:
      - postgres
    ports:
      - '8081:8080'
      - '5555:5555'
    env_file:
      - ./api/.env
    links:
      - postgres

  # nndak-ui:
  #   build: ./ui
  #   restart:  always
  #   depends_on:
  #     - nndak-api
  #   ports:
  #     - '8082:80'
  #   links:
  #     - nndak-api

  hapi-fhir-jpa:
    image: hapiproject/hapi:latest
    container_name: hapi-fhir-jpa
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - hapi-fhir-mysql
    volumes:
      - "./hapi:/hapi"
    environment:
      SPRING_CONFIG_LOCATION: /hapi/application.yaml

  hapi-fhir-mysql:
    image: mysql:latest
    container_name: hapi-fhir-mysql
    #https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html
    command: --lower_case_table_names=1
    restart: always
    environment:
      MYSQL_DATABASE: "hapi"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "admin"
    volumes:
      - hapi-fhir-mysql:/var/lib/mysql

  
  cloud-messaging:
    build:
      context: cloud-messaging
      dockerfile: Dockerfile
    container_name: cloud-messaging
    restart: always
    # env_file: ./cloud-messaging/.env
volumes:
  db:
  hapi-fhir-mysql:
  hapi:
    external: true
